@url_dev=http://localhost:3000/v1/api
### Signup

POST {{url_dev}}/shop/signup

Content-Type: application/json

{
    "name":"Anh Anh Shop 1",
    "email": "anhanh.shop1@anhanh.com",
    "password": "abc123"
}